### PR TITLE
[WIP] Project format. Would like to discuss

### PR DESCRIPTION
**Pull request by panaman67**
Lots of changes to how we would work this. Its an extension on what we talked about in class. I would love reviews from others berfore merge.

### CODE REVIEW

**Comment by stanleyyoang** [comment]
Looks good to me. That'll be a good way to add more things on in the future if we'd like.

**Comment by panaman67** [comment]
@stanleyyoang Awesome. Should I merge now or wait for rest of group approval?

**Comment by stanleyyoang** [comment]
Eh, it's up to you ¯\_(ツ)_/¯

**Comment by panaman67** [comment]
@stanleyyoang   Ill wait. Im glad it looks good to you. Surprised you are still awake. XD. Is there a way to confirm your review> It still says you are pending. Just curious

**Comment by panaman67** [comment]
Got the green light from @stanleyyoang and @gavinhouse. merging

**Pull request merged**
